spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:shareit
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
  config:
    activate:
      on-profile: 'ci,test'

